# -*- coding: utf-8 -*-
"""Chatbot_UI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SHrrjC2T9GDpkLgVR55Gm_F3T0FVNsc
"""

!pip install flask

from flask import Flask

from flask import render_template, request, jsonify

app = Flask(__name__)

@app.get("/")
def index_get():
  return render_template("base.html")

@app.post("/predict")
def predict():
  text = request.get_json().get("message")
  response = get_response(text)
  message = {"answer" : response}
  return jsonify(message)

if __name__ == "__main__":
  app.run(debug=True)